/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type game
 */

#if !defined(__GAME_PARAM_H__INCLUDED_)
#define __GAME_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

#include "protocol.hpp"
/*Local name and the URI for the type*/
static const char* Axis_URI_game = "urn:BeanService";
static const char* Axis_TypeName_game = "game";

class protocol;
class game
{
public:
	xsd__base64Binary annotation;
	xsd__string author;
	xsd__base64Binary commandLine;
	xsd__base64Binary direction;
	xsd__string files;
	xsd__base64Binary game_picture;
	xsd__string game_picture_name;
	xsd__string game_url;
	xsd__long id;
	xsd__string name;
	xsd__boolean playerPingPresent;
	protocol* protocol_Ref;
	xsd__int publication_date;
	xsd__string publisher;
	game();
	virtual ~game();
};

#endif /* !defined(__GAME_PARAM_H__INCLUDED_)*/
