/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains implementations of the GameService3Service Exception class of the web service.
 */

#include "GameService3Service_AxisClientException.hpp"

#include <axis/AxisWrapperAPI.hpp>

GameService3Service_AxisClientException::GameService3Service_AxisClientException()
{
/* This only serves the purpose of indicating that the 
 * service has thrown an excpetion 
 */ 
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION; 
	processException(m_iExceptionCode); 
}

GameService3Service_AxisClientException::GameService3Service_AxisClientException(ISoapFault* pFault)
{
	m_iExceptionCode = AXISC_SERVICE_THROWN_EXCEPTION;
	m_pISoapFault = pFault;
	processException(pFault);}

GameService3Service_AxisClientException::GameService3Service_AxisClientException(int iExceptionCode)
{

	m_iExceptionCode = iExceptionCode;
	processException (iExceptionCode);
}

GameService3Service_AxisClientException::GameService3Service_AxisClientException(exception* e)
{
	processException (e);
}

GameService3Service_AxisClientException::GameService3Service_AxisClientException(exception* e,int iExceptionCode)
{

	processException (e, iExceptionCode);
}

GameService3Service_AxisClientException::GameService3Service_AxisClientException(string sMessage)
{
	 m_sMessage =sMessage;
}

GameService3Service_AxisClientException::~GameService3Service_AxisClientException() throw () 
{
	m_sMessage ="";
}

void GameService3Service_AxisClientException:: processException(exception* e, int iExceptionCode)
{
	m_sMessage = getMessage (e) + getMessage (iExceptionCode);
}

void GameService3Service_AxisClientException::processException (ISoapFault* pFault)
{
	/*User can do something like deserializing the struct into a string*/
}

void GameService3Service_AxisClientException::processException(exception* e)
{
	m_sMessage = getMessage (e);
}

void GameService3Service_AxisClientException::processException(int iExceptionCode)
{
	m_sMessage = getMessage (iExceptionCode);
}

const string GameService3Service_AxisClientException::getMessage (exception* objException)
{
	string sMessage = objException->what();
	return sMessage;
}

const string GameService3Service_AxisClientException::getMessage (int iExceptionCode)
{
	string sMessage;
	switch(iExceptionCode)
	{
		case AXISC_SERVICE_THROWN_EXCEPTION:
		sMessage = "The GameService3Service service has thrown an exception. see details";
		break;
		default:
		sMessage = "Unknown Exception has occured in the GameService3Service service";
	}
return sMessage;
}

const char* GameService3Service_AxisClientException::what() throw ()
{
	return m_sMessage.c_str ();
}

const int GameService3Service_AxisClientException::getExceptionCode(){
	return m_iExceptionCode;
}

const ISoapFault* GameService3Service_AxisClientException::getFault(){
	return m_pISoapFault;
}

