/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type game_Array
 */

#if !defined(__GAME_ARRAY_ARRAY_H__INCLUDED_)
#define __GAME_ARRAY_ARRAY_H__INCLUDED_

class game;

typedef struct game_ArrayTag
{
	game* m_Array;
	int m_Size;
} game_Array;

#endif /* !defined(__GAME_ARRAY_ARRAY_H__INCLUDED_)*/
