/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type playerShortInfo_Array
 */

#if !defined(__PLAYERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_)
#define __PLAYERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_

class playerShortInfo;

typedef struct playerShortInfo_ArrayTag
{
	playerShortInfo* m_Array;
	int m_Size;
} playerShortInfo_Array;

#endif /* !defined(__PLAYERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_)*/
