/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type playerShortInfo
 */

#if !defined(__PLAYERSHORTINFO_PARAM_H__INCLUDED_)
#define __PLAYERSHORTINFO_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_playerShortInfo = "urn:BeanService";
static const char* Axis_TypeName_playerShortInfo = "playerShortInfo";

class playerShortInfo
{
public:
	xsd__base64Binary fullName;
	xsd__int ping;
	xsd__int score;
	playerShortInfo();
	virtual ~playerShortInfo();
};

#endif /* !defined(__PLAYERSHORTINFO_PARAM_H__INCLUDED_)*/
