/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type protocol
 */

#if !defined(__PROTOCOL_PARAM_H__INCLUDED_)
#define __PROTOCOL_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_protocol = "urn:BeanService";
static const char* Axis_TypeName_protocol = "protocol";

class protocol
{
public:
	xsd__string className;
	xsd__long id;
	xsd__string name;
	protocol();
	virtual ~protocol();
};

#endif /* !defined(__PROTOCOL_PARAM_H__INCLUDED_)*/
