/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type rule_Array
 */

#if !defined(__RULE_ARRAY_ARRAY_H__INCLUDED_)
#define __RULE_ARRAY_ARRAY_H__INCLUDED_

class rule;

typedef struct rule_ArrayTag
{
	rule* m_Array;
	int m_Size;
} rule_Array;

#endif /* !defined(__RULE_ARRAY_ARRAY_H__INCLUDED_)*/
