/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type rule
 */

#if !defined(__RULE_PARAM_H__INCLUDED_)
#define __RULE_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_rule = "urn:BeanService";
static const char* Axis_TypeName_rule = "rule";

class rule
{
public:
	xsd__base64Binary key;
	xsd__base64Binary value;
	rule();
	virtual ~rule();
};

#endif /* !defined(__RULE_PARAM_H__INCLUDED_)*/
