/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serversRoutine_Array
 */

#if !defined(__SERVERSROUTINE_ARRAY_ARRAY_H__INCLUDED_)
#define __SERVERSROUTINE_ARRAY_ARRAY_H__INCLUDED_

class serversRoutine;

typedef struct serversRoutine_ArrayTag
{
	serversRoutine* m_Array;
	int m_Size;
} serversRoutine_Array;

#endif /* !defined(__SERVERSROUTINE_ARRAY_ARRAY_H__INCLUDED_)*/
