/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serverUpdateInfo
 */

#if !defined(__SERVERUPDATEINFO_PARAM_H__INCLUDED_)
#define __SERVERUPDATEINFO_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

#include "playerShortInfo_Array.hpp"
#include "playerShortInfo.hpp"
/*Local name and the URI for the type*/
static const char* Axis_URI_serverUpdateInfo = "urn:BeanService";
static const char* Axis_TypeName_serverUpdateInfo = "serverUpdateInfo";

class serverUpdateInfo
{
public:
	xsd__boolean active;
	xsd__int changeStatus;
	xsd__long id;
	xsd__string map;
	xsd__int maxPlayer;
	playerShortInfo_Array players;
	xsd__int sessionId;
	xsd__string sessionName;
	serverUpdateInfo();
	virtual ~serverUpdateInfo();
};

#endif /* !defined(__SERVERUPDATEINFO_PARAM_H__INCLUDED_)*/
