/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serversRoutine
 */

#include "serversRoutine.hpp"
#include <axis/AxisWrapperAPI.hpp>

/*
 * This static method serialize a serversRoutine type of object
 */
int Axis_Serialize_serversRoutine(serversRoutine* param, IWrapperSoapSerializer* pSZ, bool bArray = false)
{
	if (bArray)
	{
		pSZ->serialize("<", Axis_TypeName_serversRoutine, ">", NULL);
	}
	else
	{
		const AxisChar* sPrefix = pSZ->getNamespacePrefix(Axis_URI_serversRoutine);
		pSZ->serialize("<", Axis_TypeName_serversRoutine, " xsi:type=\"", sPrefix, ":",
			Axis_TypeName_serversRoutine, "\" xmlns:", sPrefix, "=\"",
			Axis_URI_serversRoutine, "\">", NULL);
	}

	pSZ->serializeAsElement("id", (void*)&(param->id), XSD_LONG);
	pSZ->serializeAsElement("name", (void*)&(param->name), XSD_STRING);

	pSZ->serialize("</", Axis_TypeName_serversRoutine, ">", NULL);
	return AXIS_SUCCESS;
}

/*
 * This static method deserialize a serversRoutine type of object
 */
int Axis_DeSerialize_serversRoutine(serversRoutine* param, IWrapperSoapDeSerializer* pIWSDZ)
{
	param->id = pIWSDZ->getElementAsLong("id",0);
	param->name = pIWSDZ->getElementAsString("name",0);
	return pIWSDZ->getStatus();
}
void* Axis_Create_serversRoutine(serversRoutine* pObj, bool bArray = false, int nSize=0)
{
	if (bArray && (nSize > 0))
	{
		if (pObj)
		{
			serversRoutine* pNew = new serversRoutine[nSize];
			memcpy(pNew, pObj, sizeof(serversRoutine)*nSize/2);
			memset(pObj, 0, sizeof(serversRoutine)*nSize/2);
			delete [] pObj;
			return pNew;
		}
		else
		{
			return new serversRoutine[nSize];
		}
	}
	else
		return new serversRoutine;
}

/*
 * This static method delete a serversRoutine type of object
 */
void Axis_Delete_serversRoutine(serversRoutine* param, bool bArray = false, int nSize=0)
{
	if (bArray)
	{
		delete [] param;
	}
	else
	{
		delete param;
	}
}
/*
 * This static method gives the size of serversRoutine type of object
 */
int Axis_GetSize_serversRoutine()
{
	return sizeof(serversRoutine);
}

serversRoutine::serversRoutine()
{
	/*do not allocate memory to any pointer members here
	 because deserializer will allocate memory anyway. */
	memset( &id, 0, sizeof( xsd__long));
	memset( &name, 0, sizeof( xsd__string));
}

serversRoutine::~serversRoutine()
{
	/*delete any pointer and array members here*/
}
