/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serverShortInfo_Array
 */

#if !defined(__SERVERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_)
#define __SERVERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_

class serverShortInfo;

typedef struct serverShortInfo_ArrayTag
{
	serverShortInfo* m_Array;
	int m_Size;
} serverShortInfo_Array;

#endif /* !defined(__SERVERSHORTINFO_ARRAY_ARRAY_H__INCLUDED_)*/
