/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serverAddress_Array
 */

#if !defined(__SERVERADDRESS_ARRAY_ARRAY_H__INCLUDED_)
#define __SERVERADDRESS_ARRAY_ARRAY_H__INCLUDED_

class serverAddress;

typedef struct serverAddress_ArrayTag
{
	serverAddress* m_Array;
	int m_Size;
} serverAddress_Array;

#endif /* !defined(__SERVERADDRESS_ARRAY_ARRAY_H__INCLUDED_)*/
