/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains functions to manipulate complex type serversRoutine
 */

#if !defined(__SERVERSROUTINE_PARAM_H__INCLUDED_)
#define __SERVERSROUTINE_PARAM_H__INCLUDED_

#include <axis/AxisUserAPI.hpp>
AXIS_CPP_NAMESPACE_USE 

/*Local name and the URI for the type*/
static const char* Axis_URI_serversRoutine = "urn:BeanService";
static const char* Axis_TypeName_serversRoutine = "serversRoutine";

class serversRoutine
{
public:
	xsd__long id;
	xsd__string name;
	serversRoutine();
	virtual ~serversRoutine();
};

#endif /* !defined(__SERVERSROUTINE_PARAM_H__INCLUDED_)*/
